/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TugasOOP;

/**
 *
 * @author Muhammad Adif Fikri || 1910631170101
 */
public class TugasOopGUI extends javax.swing.JFrame {
    HistoryCollection h = new HistoryCollection();
    BangunRuang br = new BangunRuang();

    /**
     * Creates new form TugasOopGUI
     */
    public TugasOopGUI() {
        initComponents();
        ta_history.setEditable(false);
    }
    
    public void historyCollection(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_parameter1 = new javax.swing.JLabel();
        cb_bangun = new javax.swing.JComboBox<>();
        l_parameter2 = new javax.swing.JLabel();
        tf_parameter1 = new javax.swing.JTextField();
        l_parameter3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_parameter2 = new javax.swing.JTextField();
        tf_parameter3 = new javax.swing.JTextField();
        l_hasil1 = new javax.swing.JLabel();
        bt_hitung = new javax.swing.JButton();
        bt_reset = new javax.swing.JButton();
        l_hasil2 = new javax.swing.JLabel();
        l_hasil3 = new javax.swing.JLabel();
        tf_hasil1 = new javax.swing.JTextField();
        tf_hasil2 = new javax.swing.JTextField();
        tf_hasil3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_history = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Perhitungan Luas, Keliling, dan Volume");

        jLabel2.setText("Pilih Bangun :");

        l_parameter1.setText("Panjang");

        cb_bangun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Persegi Panjang", "Persegi", "Segitiga", "Lingkaran", "Jajar Genjang" }));
        cb_bangun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bangunActionPerformed(evt);
            }
        });

        l_parameter2.setText("Lebar");

        l_parameter3.setText("Tinggi");

        jLabel6.setText("Hasil Perhitungan :");

        l_hasil1.setText("Luas");

        bt_hitung.setText("Hitung");
        bt_hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_hitungActionPerformed(evt);
            }
        });

        bt_reset.setText("Reset");
        bt_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_resetActionPerformed(evt);
            }
        });

        l_hasil2.setText("Keliling");

        l_hasil3.setText("Volume");

        tf_hasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_hasil2ActionPerformed(evt);
            }
        });

        jLabel3.setText("List History Perhitungan");

        ta_history.setColumns(20);
        ta_history.setRows(5);
        jScrollPane1.setViewportView(ta_history);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(23, 23, 23)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6)
                                        .addComponent(l_parameter1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(l_parameter2)
                                            .addComponent(l_parameter3)))
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cb_bangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_parameter1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_parameter2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_parameter3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(bt_hitung)
                                    .addGap(18, 18, 18)
                                    .addComponent(bt_reset)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(l_hasil2)
                                    .addComponent(l_hasil1)
                                    .addComponent(l_hasil3))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tf_hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_hasil2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_hasil3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(jLabel3)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cb_bangun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_parameter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_parameter1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_parameter2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_parameter2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_parameter3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_parameter3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt_hitung)
                                    .addComponent(bt_reset))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(l_hasil1)
                                    .addComponent(tf_hasil1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_hasil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_hasil2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tf_hasil3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(l_hasil3)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1)))
                        .addGap(22, 22, 22))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_bangunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bangunActionPerformed
        // TODO add your handling code here:
        tf_parameter1.setText("");
        tf_parameter2.setText("");
        tf_parameter3.setText("");
        
        switch (cb_bangun.getSelectedItem().toString()) {
            case "Persegi":
                l_parameter1.setText("Sisi");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("-");
                tf_parameter2.setEditable(false);
                l_parameter3.setText("-");
                tf_parameter3.setEditable(false);
                break;
            case "Persegi Panjang":
                l_parameter1.setText("Panjang");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("Lebar");
                tf_parameter2.setEditable(true);
                l_parameter3.setText("Tinggi");
                tf_parameter3.setEditable(true);
                break;
            case "Segitiga":
                l_parameter1.setText("Alas");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("Tinggi");
                tf_parameter2.setEditable(true);
                l_parameter3.setText("Tinggi Limas");
                tf_parameter3.setEditable(true);
                break;
            case "Lingkaran":
                l_parameter1.setText("Jari-jari");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("Tinggi");
                tf_parameter2.setVisible(true);
                l_parameter3.setText("-");
                tf_parameter3.setEditable(false);
                break;
            case "Jajar Genjang":
                l_parameter1.setText("Panjang");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("Sisi Miring");
                tf_parameter2.setEditable(true);
                l_parameter3.setText("Tinggi");
                tf_parameter3.setEditable(true);
                break;
            default:
                l_parameter1.setText("Panjang");
                tf_parameter1.setEditable(true);
                l_parameter2.setText("Lebar");
                tf_parameter2.setEditable(true);
                l_parameter3.setText("Tinggi");
                tf_parameter3.setEditable(true);
                break;
        }
    }//GEN-LAST:event_cb_bangunActionPerformed

    private void bt_hitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_hitungActionPerformed
        // TODO add your handling code here:
        if (cb_bangun.getSelectedItem().toString().equals("Persegi")) {
            int sisi = Integer.parseInt(tf_parameter1.getText());
            tf_hasil1.setText(String.valueOf(br.hitLuas(sisi)));
            tf_hasil2.setText(String.valueOf(br.hitKel(sisi)));
            tf_hasil3.setText(String.valueOf(br.hitVol(sisi)));
            String nama   = "Bangun\t: " + cb_bangun.getSelectedItem().toString();
            String param1 = l_parameter1.getText() + "\t: " + tf_parameter1.getText();
            String hasil1 = l_hasil1.getText() + "\t= " + tf_hasil1.getText();
            String hasil2 = l_hasil2.getText() + "\t= " + tf_hasil2.getText();
            String hasil3 = l_hasil3.getText() + "\t= " + tf_hasil3.getText();
            h.listTambah(nama, param1, hasil1, hasil2, hasil3);
        }
        else if (cb_bangun.getSelectedItem().toString().equals("Persegi Panjang")) {
            int panjang = Integer.parseInt(tf_parameter1.getText());
            int lebar = Integer.parseInt(tf_parameter2.getText());
            int tinggi = Integer.parseInt(tf_parameter3.getText());
            tf_hasil1.setText(String.valueOf(br.hitLuas(panjang, lebar)));
            tf_hasil2.setText(String.valueOf(br.hitKel(panjang, lebar)));
            tf_hasil3.setText(String.valueOf(br.hitVol(panjang, lebar, tinggi)));
            String nama   = "Bangun\t: " + cb_bangun.getSelectedItem().toString();
            String param1 = l_parameter1.getText() + "\t: " + tf_parameter1.getText();
            String param2 = l_parameter2.getText() + "\t: " + tf_parameter2.getText();
            String param3 = l_parameter3.getText() + "\t: " + tf_parameter3.getText();
            String hasil1 = l_hasil1.getText() + "\t= " + tf_hasil1.getText();
            String hasil2 = l_hasil2.getText() + "\t= " + tf_hasil2.getText();
            String hasil3 = l_hasil3.getText() + "\t= " + tf_hasil3.getText();
            h.listTambah(nama, param1, param2, param3, hasil1, hasil2, hasil3);
        }
        else if (cb_bangun.getSelectedItem().toString().equals("Segitiga")) {
            int alas = Integer.parseInt(tf_parameter1.getText());
            int tinggi = Integer.parseInt(tf_parameter3.getText());
            Double tAlas = Double.parseDouble(tf_parameter2.getText());
            tf_hasil1.setText(String.valueOf(br.hitLuas(alas, tAlas)));
            tf_hasil2.setText(String.valueOf(br.hitKel(alas, alas, alas)));
            tf_hasil3.setText(String.valueOf(br.hitVol(alas, tinggi, tAlas)));
            String nama   = "Bangun\t: " + cb_bangun.getSelectedItem().toString();
            String param1 = l_parameter1.getText() + "\t: " + tf_parameter1.getText();
            String param2 = l_parameter2.getText() + "\t: " + tf_parameter2.getText();
            String param3 = l_parameter3.getText() + "\t: " + tf_parameter3.getText();
            String hasil1 = l_hasil1.getText() + "\t= " + tf_hasil1.getText();
            String hasil2 = l_hasil2.getText() + "\t= " + tf_hasil2.getText();
            String hasil3 = l_hasil3.getText() + "\t= " + tf_hasil3.getText();
            h.listTambah(nama, param1, param2, param3, hasil1, hasil2, hasil3);
        }
        else if (cb_bangun.getSelectedItem().toString().equals("Lingkaran")) {
            Double r = Double.parseDouble(tf_parameter1.getText());
            int tinggi = Integer.parseInt(tf_parameter2.getText());
            tf_hasil1.setText(String.valueOf(br.hitLuas(r)));
            tf_hasil2.setText(String.valueOf(br.hitKel(r)));
            tf_hasil3.setText(String.valueOf(br.hitVol(r, tinggi)));
            String nama   = "Bangun\t: " + cb_bangun.getSelectedItem().toString();
            String param1 = l_parameter1.getText() + "\t: " + tf_parameter1.getText();
            String param2 = l_parameter2.getText() + "\t: " + tf_parameter2.getText();
            String hasil1 = l_hasil1.getText() + "\t= " + tf_hasil1.getText();
            String hasil2 = l_hasil2.getText() + "\t= " + tf_hasil2.getText();
            String hasil3 = l_hasil3.getText() + "\t= " + tf_hasil3.getText();
            h.listTambah(nama, param1, param2, hasil1, hasil2, hasil3);
        }
        else if (cb_bangun.getSelectedItem().toString().equals("Jajar Genjang")) {
            int panjang = Integer.parseInt(tf_parameter1.getText());
            int lebar = Integer.parseInt(tf_parameter2.getText());
            Double tinggi = Double.parseDouble(tf_parameter3.getText());
            tf_hasil1.setText(String.valueOf(br.hitLuas(tinggi, lebar)));
            tf_hasil2.setText(String.valueOf(br.hitKel(panjang, lebar, tinggi)));
            tf_hasil3.setText("-");
            String nama   = "Bangun\t: " + cb_bangun.getSelectedItem().toString();
            String param1 = l_parameter1.getText() + "\t: " + tf_parameter1.getText();
            String param2 = l_parameter2.getText() + "\t: " + tf_parameter2.getText();
            String param3 = l_parameter3.getText() + "\t: " + tf_parameter3.getText();
            String hasil1 = l_hasil1.getText() + "\t= " + tf_hasil1.getText();
            String hasil2 = l_hasil2.getText() + "\t= " + tf_hasil2.getText();
            String hasil3 = l_hasil3.getText() + "\t= " + tf_hasil3.getText();
            h.listTambah(nama, param1, param2, param3, hasil1, hasil2, hasil3);
        }
        
        ta_history.setText("");
        for (int i = 0; i < h.list.size(); i++) {
            ta_history.append(h.list.get(i)+"\n");
        }
    }//GEN-LAST:event_bt_hitungActionPerformed

    private void bt_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_resetActionPerformed
        // TODO add your handling code here:
        tf_parameter1.setText("");
        tf_parameter2.setText("");
        tf_parameter3.setText("");
        tf_hasil1.setText("");
        tf_hasil2.setText("");
        tf_hasil3.setText("");
    }//GEN-LAST:event_bt_resetActionPerformed

    private void tf_hasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_hasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_hasil2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasOopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasOopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasOopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasOopGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasOopGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_hitung;
    private javax.swing.JButton bt_reset;
    private javax.swing.JComboBox<String> cb_bangun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_hasil1;
    private javax.swing.JLabel l_hasil2;
    private javax.swing.JLabel l_hasil3;
    private javax.swing.JLabel l_parameter1;
    private javax.swing.JLabel l_parameter2;
    private javax.swing.JLabel l_parameter3;
    private javax.swing.JTextArea ta_history;
    private javax.swing.JTextField tf_hasil1;
    private javax.swing.JTextField tf_hasil2;
    private javax.swing.JTextField tf_hasil3;
    private javax.swing.JTextField tf_parameter1;
    private javax.swing.JTextField tf_parameter2;
    private javax.swing.JTextField tf_parameter3;
    // End of variables declaration//GEN-END:variables
}
